- id: '1655714129517'
  alias: Config-G-Schalter
  description: ''
  use_blueprint:
    path: Stringer/zigbee2mqtt-sonoff-wireless-switch-snzb-01.yaml
    input:
      switch: sensor.g_schalter_action
      single_press:
      - if:
        - condition: state
          entity_id: light.g_lampe
          state: 'off'
        - condition: device
          type: is_off
          device_id: 203c596c57e490537440e06c29d674ba
          entity_id: switch.g_tischlampe
          domain: switch
        then:
        - service: scene.turn_on
          target:
            entity_id: scene.g_indirekt
          metadata: {}
        else:
        - service: scene.turn_on
          target:
            entity_id: scene.g_aus
          metadata: {}
      double_press:
      - service: script.sf_aus_licht_delay_gang
        data: {}
      long_press:
      - service: script.sf_aus_licht_delay_gang
        data: {}
- id: '1655915183866'
  alias: Config-SZ-Schalter
  description: ''
  use_blueprint:
    path: harbri/z2m-philips-hue-dimmer-switch-individual-buttons.yaml
    input:
      dimmer: sensor.sz_schalter_action
      button_1:
      - service: scene.turn_on
        target:
          entity_id: scene.sz_normal
        metadata: {}
      button_2:
      - service: scene.turn_on
        target:
          entity_id: scene.sz_hell
        metadata: {}
      button_3:
      - service: scene.turn_on
        target:
          entity_id: scene.sz_indirekt
        metadata: {}
      button_4:
      - service: scene.turn_on
        target:
          entity_id: scene.sz_aus
        metadata: {}
      button_5:
      - service: scene.turn_on
        target:
          entity_id: scene.sz_hell
        metadata: {}
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: scene.turn_on
        target:
          entity_id: scene.sz_aus
        metadata: {}
