decluttering_templates: !include_dir_merge_named templates

views:
- type: custom:vertical-layout
  theme: Backend-selected
  cards: 
    
  - type: custom:decluttering-card
    template: template_card
    variables:
    - room: wz

  - type: custom:decluttering-card
    template: template_card
    variables:
    - room: sz
    
  - type: custom:decluttering-card
    template: template_card
    variables:
    - room: k

  - type: custom:decluttering-card
    template: template_card_art