google_assistant: 
  project_id: !secret google_project_id
  service_account: !include /config/.storage/google_assistant_auth.json
  report_state: true
  exposed_domains:
    - scene
    - script
  entity_config:
      light.wz_beleuchtung:
        expose: true
      light.sz_beleuchtung:
        expose: true
      light.g_beleuchtung:
        expose: true
      light.k_beleuchtung:
        expose: true
      switch.bett: 
        expose: true
      switch.heizdecke: 
        expose: true
      switch.sofa: 
        expose: true
      switch.wz_luftung: 
        expose: true
      switch.sz_luftung: 
        expose: true
      fan.wz_ventilator:
        expose: false
      fan.sz_ventilator:
        expose: false