calendar:
  - platform: caldav
    username: !secret acc_apple_icloud_user
    password: !secret acc_apple_icloud_password
    url: https://caldav.icloud.com
    calendars:
    - "Privat"
    - "Daten und Zeiträume"