frontend: 
  extra_module_url: 
  - /hacsfiles/lovelace-card-mod/card-mod.js
  - /hacsfiles/ha-custom-sidebar/ha-custom-sidebar.js

lovelace:
  mode: yaml

  resources:
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/lovelace-badge-card/badge-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js 
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module