http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.178.0/24
    - 172.30.32.0/24
    - 172.30.33.0/24
    - ::1
    - ::1/128
    - "fe80::/10"
    - "fd00::8"
    # - !secret ha_config_http_trusted_proxies_external