logger: 
  default: error
  logs:
    custom_components.pyscript: info
    py: info
    pychromecast.socket_client: critical

  filters:
    custom_components.pyscript:
      - "Unloaded"
    custom_components.pyscript.global_ctx:
      - "Loaded"
      - "Reloaded"
    custom_components.pyscript.trigger:
      - "will never trigger"
    homeassistant: 
      - "Future exception was never retrieved"
    homeassistant.components.braviatv.coordinator:
      - "braviatv"
    homeassistant.components.command_line.utils: 
      - "Timeout for command: python3"
    homeassistant.components.google_assistant.http: 
      - "googleapis.com"
    homeassistant.components.hassio:
      - "/addons"
    homeassistant.components.hassio.handlers:
      - "/addons"
    homeassistant.components.websocket_api.http.connection:
      - "not found"
      - "Unexpected error inside websocket API"
    homeassistant.helpers.entity:
      - "Update"
    homeassistant.helpers.script.websocket_api_script:
      - "Service not found for call_service"
    custom_components.tapo.coordinators:
      - "Unexpected exception"
    custom_components.xiaomi_miot.fan:
      - "MiioException"
    custom_components.xiaomi_miot.humidifier:
      - "MiioException"
    aiohttp.server:
      - "Error handling request"
    habluetooth.scanner:
      - "org.bluez.Error.InProgress"
    miio.miioprotocol:
      - "error"
    py.warnings:
      - "EvalFuncVar.__call__"
      - "Unverified HTTPS request"
    root:
      - "DTSTAMP"
      - "Ical data was modified"
      - "BEGIN:VEVENT"

recorder:
  auto_purge: true
  auto_repack: true
  purge_keep_days: 1
  commit_interval: 45
  include:
    domains:
    - pyscript
    entities:
    - switch.bett
    - switch.sofa
    - switch.heizdecke
    - sensor.sofa_current_power
    entity_globs:
    - fritz_box_*_durchsatz
    - sensor.system_monitor_*
    - sensor.*temperature

  exclude: 
    entities: 
      - sensor.graph_fix_up_temperature
      - sensor.graph_fix_down_temperature

system_log:
  max_entries: 3