logger: 
  default: error
  logs:
    custom_components.pyscript: info

  filters:
    custom_components.pyscript:
      - "Unloaded"
    custom_components.pyscript.global_ctx:
      - "Loaded"
      - "Reloaded"

    homeassistant.components.command_line.utils: 
      - "Timeout for command: python3"
    custom_components.xiaomi_miot.fan:
      - "MiioException"
    custom_components.xiaomi_miot.humidifier:
      - "MiioException"
    habluetooth.scanner:
      - "org.bluez.Error.InProgress"

recorder:
  auto_purge: true
  auto_repack: true
  purge_keep_days: 1
  commit_interval: 60
  include:
    domains:
    - pyscript
    entities:
    - switch.bett
    - switch.sofa
    - switch.heizdecke
    entity_globs:
    - sensor.*temperature
    - fritz_box_*_durchsatz
    - sensor.system_monitor_*

system_log:
  max_entries: 3