logger: 
  default: error
  logs:
    custom_components.pyscript: info
    pychromecast.socket_client: critical

  filters:
    custom_components.pyscript:
      - "Unloaded"
    custom_components.pyscript.global_ctx:
      - "Loaded"
      # - "Reloaded"
    custom_components.pyscript.trigger:
      - "will never trigger"
    homeassistant.components.command_line.utils: 
      - "Timeout for command: python3"
    homeassistant.components.google_assistant.http: 
      - "googleapis.com"
    homeassistant.helpers.script.websocket_api_script:
      - "Service not found for call_service"
    custom_components.tapo.coordinators:
      - "Unexpected exception"
    custom_components.xiaomi_miot.fan:
      - "MiioException"
    custom_components.xiaomi_miot.humidifier:
      - "MiioException"
    aiohttp.server:
      - "Error handling request"
    habluetooth.scanner:
      - "org.bluez.Error.InProgress"

recorder:
  auto_purge: true
  auto_repack: true
  purge_keep_days: 1
  commit_interval: 45
  include:
    domains:
    - pyscript
    entities:
    - switch.bett
    - switch.sofa
    - switch.heizdecke
    entity_globs:
    - sensor.*temperature
    - fritz_box_*_durchsatz
    - sensor.system_monitor_*

system_log:
  max_entries: 3