pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    app_debug: 
    - name: app_debug
    air_control: 
    - name: air_control
    git_sync: 
    - name: git_sync
    scrape_housing: 
    - name: scrape_housing
    service_init: 
    - name: services_init
    tests:
    - name: tests