pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    app: 
      - name: app
    scrape: 
      - name: scrape
    services: 
      - name: services
    sync_git: 
      - name: sync_git