pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    app_debug: 
    - name: app_debug
    air_control: 
    - name: air_control
    run_tests: 
    - name: run_tests
    scrape_housing: 
    - name: scrape_housing
    subprocesses: 
    - name: subprocesses
