pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    app_debug: 
    - name: app_debug
    air_control: 
    - name: air_control
    sync_git: 
    - name: sync_git
    scrape_housing: 
    - name: scrape_housing
    init_services: 
    - name: init_services
    run_tests:
    - name: run_tests