recorder:
  auto_purge: true
  auto_repack: true
  purge_keep_days: 1
  commit_interval: 45
  include:
    domains:
    - scripts
    - pyscript
    - sensor
    entities:
    - switch.bett
    - switch.sofa
    - switch.heizdecke
    entity_globs:
    - sensor.*temperature
    - fritz_box_*_durchsatz
    - sensor.system_monitor_*
    - sensor.*_window