recorder:
  auto_purge: true
  auto_repack: true
  commit_interval: 600
  purge_keep_days: 3
  include:
    domains:
      - scripts
      - pyscript
    entity_globs:
      - binary_sensor.*_occupancy
    entities:
      - switch.bett
      - switch.sofa
      - switch.heizdecke