shell_command:
<<<<<<< Updated upstream
  filebackup: 'bash /config/pyscript/ressources/bash/filebackup.sh > /dev/null 2>&1 &'
=======
  ha_filebackup: 'bash /config/pyscript/ressources/bash/filebackup.sh > /dev/null 2>&1 &'
>>>>>>> Stashed changes
